Description of normvector
Home > example_initialization_normals > src > math > normvector.m
normvector
SYNOPSIS
function normv = normvector(x,d)
DESCRIPTION
% Lagadic Team -- Inria Sophia Antipolis
  Renato Martins 2017
  Email: renatojmsdh@gmail.com
  Use: compute norm 2 of vector/matrix along dimension d
  Inputs: - (vector) x
          - (int) d = 1 (by column), d = 2 (by row)
  Output: norm 2 of the vector matrix
%
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
compute_translation % Lagadic Team -- Inria Sophia Antipolis
normals_centered % Lagadic Team -- Inria Sophia Antipolis
p3D_pixel % Lagadic Team -- Inria Sophia Antipolis
SOURCE CODE
%% Lagadic Team -- Inria Sophia Antipolis
%  Renato Martins 2017
%  Email: renatojmsdh@gmail.com
%
%  Use: compute norm 2 of vector/matrix along dimension d
%  Inputs: - (vector) x
%          - (int) d = 1 (by column), d = 2 (by row)
%  Output: norm 2 of the vector matrix
%
%%
function normv = normvector(x,d)
normv = sqrt(sum(x.^2,d));
end