Description of rad2deg
Home > example_initialization_normals > src > math > rad2deg.m
rad2deg
SYNOPSIS
function deg = rad2deg(angle)
DESCRIPTION
% Lagadic Team -- Inria Sophia Antipolis
  rmartins 2017
  Use: convert randians to degrees
  Input: -(vector) the angle in radians
  Output: the angles in degrees
%
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
example_initialization_normals % Lagadic Team -- Inria Sophia Antipolis
compute_translation % Lagadic Team -- Inria Sophia Antipolis
findInliersRot_new % Lagadic Team -- Inria Sophia Antipolis
SOURCE CODE
%% Lagadic Team -- Inria Sophia Antipolis
%  rmartins 2017
%
%  Use: convert randians to degrees
%  Input: -(vector) the angle in radians
%  Output: the angles in degrees
%
%%
function deg = rad2deg(angle)
deg = angle*180/pi;
end